/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docs: [{ type: 'autogenerated', dirName: 'developer' }],
  trader: [{ type: 'autogenerated', dirName: 'trader' }],
  tradingview: [{ type: 'autogenerated', dirName: 'tradingview' }],
  // trader: [
  //   {
  //   type: 'category',
  //   label: 'Trader',
  //   link: {
  //     type: 'generated-index',
  //     title: 'Docusaurus Guides',
  //     description: 'Learn about the most important Docusaurus concepts!',
  //     // slug: '/trader/guide',
  //     keywords: ['traders'],
  //     image: '/img/1-all-in-one.png',
  //   },
  //   items: [{
  //     type: 'autogenerated',
  //     dirName: 'trader',
  //   },],
  // }
  // ],
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
  // api: [
  //   {
  //     type: 'category',
  //     label: "Trader",
  //     // dirName: 'trader',
  //     items: [{
  //       type: 'autogenerated',
  //       dirName: 'trader/guide', // Generate sidebar slice from docs/tutorials/easy
  //     }],
  //   },
  // ],
};
